############## General ############################################
server:
  port: 1488
###################################################################

############## Database ###########################################
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2-resource-server
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
    database: postgresql

  flyway:
    enabled: false
###################################################################
