############## General ############################################
server:
  port: 8888
###################################################################

############## Database ###########################################
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2-resource-server
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true

  flyway:
    enabled: false
###################################################################

############## Database ###########################################
auth:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/oauth2-auth-server
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
###################################################################
